weather_project/weather_app/urls.py
from django.urls import path
from . import views

app_name = "weather_app"

urlpatterns = [
    path("", views.home, name="home"),
    path("cities/", views.CityListView.as_view(), name="city_list"),
    path("weather/", views.WeatherListView.as_view(), name="weather_list"),
    path("contact/", views.contact, name="contact"),
    path("thanks/", views.thanks, name="thanks"),
    path("add_city/", views.add_city, name="add_city"),
]

weather_project/weather_project/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = "weather_app"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("weather_app.urls")),
]

weather_project/weather_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name
    
class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class ProfileUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    bio = models.TextField(blank=True)
    role = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.user.username
    
class Event(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='events') #OneToMany
    description = models.TextField(blank=True)
    date_start = models.DateField()
    date_end = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=200, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name='events') #ManyToMany

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('weather_app:event_detail', kwargs={'pk': self.pk})
    
class Record(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='records') #OneToMany
    date = models.DateField()
    temperature = models.FloatField(null=True, blank=True)
    humidity = models.FloatField(null=True, blank=True)
    note = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"{self.event.title} - {self.date}"

class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.name}, {self.country}" if self.country else self.name

class WeatherData(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    date = models.DateField()
    temperature = models.FloatField()
    humidity = models.FloatField()
    description = models.CharField(max_length=255)

    def __str__(self):
        return f"El tiempo en {self.city.name} el día {self.date}: {self.temperature}°C, {self.humidity}%, {self.description}"

weather_project/weather_app/forms.py
from django import forms
from .models import Event, Record, Category, City
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ['date', 'temperature', 'humidity', 'note']
        widgets = {'date': forms.DateInput(attrs={'type':'date'})}

class ContactForm(forms.Form):
    name = forms.CharField(label="Nombre", max_length=100)
    email = forms.EmailField(label="Correo electrónico")
    comment = forms.CharField(label="Comentario", widget=forms.Textarea)

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class AddCityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ["name", "country"]
        labels = {
            "name": "Nombre de la ciudad/pueblo",
            "country": "Provincia",
        }

weather_project/weather_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import City, WeatherData
from .forms import ContactForm
from .forms import ContactForm, AddCityForm

def home(request):
    return render(request, "weather_app/home.html")

class CityListView(ListView):
    model = City
    template_name = "weather_app/city_list.html"
    context_object_name = "cities"

class WeatherListView(ListView):
    model = WeatherData
    template_name = "weather_app/weather_list.html"
    context_object_name = "weathers"

def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            return redirect("weather_app:thanks")
    else:
        form = ContactForm()
    return render(request, "weather_app/contact.html", {"form": form})

def thanks(request):
    return render(request, "weather_app/thanks.html")

def add_city(request):
    if request.method == "POST":
        form = AddCityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("weather_app:city_list")
    else:
        form = AddCityForm()

    return render(request, "weather_app/add_city.html", {"form": form})

weather_project/weather_app/templates/weather_app/add_city.html
{% extends "weather_app/base.html" %}

{% block content %}
<h2>No encuentras tu ciudad?</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Agregar ciudad/pueblo</button>
</form>
{% endblock %}

weather_project/weather_app/templates/weather_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Weather Project</title>
  </head>
  <body>
    <h1>🌤 Weather Project</h1>
    <nav>
      <a href="{%url 'weather_app:home' %}">Principal</a> |
      <a href="{% url 'weather_app:city_list' %}">Ciudades</a> |
      <a href="{% url 'weather_app:weather_list' %}">Datos del tiempo</a>
    </nav>
    <hr>
    {% block content %}
    {% endblock %}
  </body>
</html>

weather_project/weather_app/templates/weather_app/city_list.html
{% extends "weather_app/base.html" %}

{% block content %}
<h2>Lista de ciudades</h2>
<ul>
    {% for city in cities %}
        <li>{{ city.name }} ({{ city.country }})</li>
    {% empty %}
        <li>No se han añadido las ciudades aún</li>
    {% endfor %}
</ul>
{% endblock %}

weather_project/weather_app/templates/weather_app/contact.html
{% extends "weather_app/base.html" %}

{% block content %}
<h2>Contacta con nosotros</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar</button>
</form>
{% endblock %}

weather_project/weather_app/templates/weather_app/home.html
{% extends "weather_app/base.html" %}

{% block content %}
<h2>Bienvenido a Weather Project</h2>

<p>No encuentras tu ciudad? <a href="{% url 'weather_app:add_city' %}">Agrégala aquí</a></p>
{% endblock %}

weather_project/weather_app/templates/weather_app/thanks.html
{% extends "weather_app/base.html" %}

{% block content %}
<h2>¡Gracias por tu mensaje!</h2>
<p>Nos pondremos en contacto contigo pronto.</p>
{% endblock %}

weather_project/weather_app/templates/weather_app/weather_list.html
{% extends "weather_app/base.html" %}

{% block content %}
<h2>Tiempo</h2>
<ul>
    {% for weather in weathers %}
        <li>
            {{ weather.city.name }} - {{ weather.date }}:
            {{ weather.temperature }}°C, {{ weather.humidity }}%, {{ weather.description }}
        </li>
    {% empty %}
        <li>No hay datos sobre el tiempo</li>
    {% endfor %}
</ul>
{% endblock %}